name: Nightly Release

on:
  workflow_dispatch: # 手动触发选项
  schedule:
    - cron: "0 22 * * *" # 每天晚上 10 点触发

jobs:
  nightly-build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 删除现有 Release 和标签（如果存在）
      - name: Delete existing Release and Tag
        uses: actions/github-script@v6
        with:
          github_token: ${{ secrets.AMZ_TOKEN }}
          script: |
            const tag = "dict-nightly";

            // 检查现有的 Release
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const existingRelease = releases.data.find(r => r.tag_name === tag);
            if (existingRelease) {
              console.log(`Deleting existing Release with ID: ${existingRelease.id}`);
              await github.rest.repos.deleteRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: existingRelease.id
              });
            } else {
              console.log("No existing Release found.");
            }

            // 删除现有的 Tag
            try {
              console.log(`Deleting tag: ${tag}`);
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `tags/${tag}`
              });
            } catch (error) {
              console.log("Tag does not exist or already deleted.");
            }

      # 确保只打包 cn_dicts 文件夹为 ZIP 文件
      - name: Create ZIP archive
        run: |
          if [ -d "cn_dicts" ]; then
            mkdir -p dist
            zip -r dist/wanxiang.dict-nightly.zip cn_dicts
            echo "ZIP archive created: dist/wanxiang.dict-nightly.zip"
          else
            echo "Error: cn_dicts folder does not exist."
            exit 1
          fi

      # 创建新的 Release
      - name: Create new Release
        id: create_release
        uses: actions/github-script@v6
        with:
          github_token: ${{ secrets.AMZ_TOKEN }}
          script: |
            const tag = "dict-nightly";
            const release = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tag,
              name: "每夜自动替换更新词库",
              body: "Nightly build release with dicts. Please download the 'wanxiang.dict-nightly.zip' asset below.",
              draft: false,
              prerelease: true
            });

            console.log("Release created:", release.data);
            core.setOutput("upload_url", release.data.upload_url);

      # 上传自定义资产
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/wanxiang.dict-nightly.zip
          asset_name: wanxiang.dict-nightly.zip
          asset_content_type: application/zip

