name: Nightly Build and Release

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: "0 22 * * *" # 每天晚上 10 点触发

jobs:
  nightly-build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 打包词库文件
      - name: Pack cn_dicts
        run: |
          mkdir -p dist
          echo "Packing cn_dicts..."
          zip -r dist/cn_dicts.zip cn_dicts
          echo "Packing completed: dist/cn_dicts.zip"

      # 删除旧的 Nightly Release（如果存在）
      - name: Delete existing Nightly Release
        uses: actions/github-script@v6
        with:
          github_token: ${{ secrets.AMZ_TOKEN }}
          script: |
            const tag = "nightly";

            // 检查现有的 Release
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const existingRelease = releases.data.find(r => r.tag_name === tag);
            if (existingRelease) {
              console.log(`Deleting existing Nightly Release with ID: ${existingRelease.id}`);
              await github.rest.repos.deleteRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: existingRelease.id
              });
            } else {
              console.log("No existing Nightly Release found.");
            }

            // 删除现有的 Tag
            try {
              console.log(`Deleting tag: ${tag}`);
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `tags/${tag}`
              });
            } catch (error) {
              console.log("Tag does not exist or already deleted.");
            }

      # 创建新的 Nightly Release
      - name: Create new Nightly Release
        uses: "softprops/action-gh-release@v2"
        with:
          tag_name: nightly
          name: "Nightly Build - Updated Dictionaries"
          body: |
            ## Nightly Dictionaries Update

            每夜构建包含以下资源：
            - `cn_dicts.zip`：最新的中文词库文件。
          files: dist/cn_dicts.zip
          draft: false
          prerelease: true

